name: clj-kondo checks

on: [push]

jobs:
  linting:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: DeLaGuardo/clojure-lint-action@master
        with:
          clj-kondo-args: --lint src test
          check-name: clj-kondo
          github_token: ${{ secrets.GITHUB_TOKEN }}
