name: Tests

on:
  push:

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Cache maven deps
        uses: actions/cache@v3.0.11
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Prepare java
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.11.1.1165

      - name: Unit Tests
        run: |
          clojure -M:test
